services:
  dev:
    build: .
    environment:
      DBT_PROFILES_DIR: /workspace/dbt
      DBT_PROJECT_DIR: /workspace/dbt
      USER: ${USER}
    env_file: .env
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
