CREATE TEMPORARY TABLE volunteers_delete_cf835a97662b221b5f93f1669e0c9b31 AS SELECT d."_dlt_id" FROM "airtable"."volunteers" as d WHERE EXISTS (SELECT 1 FROM "airtable_staging"."volunteers" as s WHERE d."id" = s."id")
DELETE FROM "airtable"."volunteers__fields__source"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__availability"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__engagement_goals"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__tech_skills"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__roles_interested_in"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__nonprofit_skills"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__race"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__skills_to_develop"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers__fields__language_select"             WHERE "_dlt_root_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
DELETE FROM "airtable"."volunteers"             WHERE "_dlt_id" IN (                 SELECT * FROM volunteers_delete_cf835a97662b221b5f93f1669e0c9b31             );         
CREATE TEMPORARY TABLE volunteers_insert_33bf230cb593a2c05e350aeabe2bb245 AS                  SELECT "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "_dlt_id"                         FROM "airtable_staging"."volunteers"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND (1 = 1)          
INSERT INTO "airtable"."volunteers"("id", "created_time", "fields__profile_update_link", "fields__last_name", "fields__volunteer_id", "fields__hours_per_month", "fields__first_name", "fields__email", "fields__project_interests", "fields__joined_date", "_dlt_load_id", "_dlt_id", "fields__slack_handle", "fields__board_leadership_experience", "fields__grant_writing_experience", "fields__state", "fields__city", "fields__nonprofit_experience_level", "fields__timezone", "fields__prior_volunteer_experience", "fields__tech_languages_tools", "fields__tech_experience_level", "fields__accommodations", "fields__employment_status", "fields__age_range", "fields__pronouns", "fields__github", "fields__other_notes", "fields__linkedin", "fields__website_portfolio", "fields__meeting_attendance") SELECT "id", "created_time", "fields__profile_update_link", "fields__last_name", "fields__volunteer_id", "fields__hours_per_month", "fields__first_name", "fields__email", "fields__project_interests", "fields__joined_date", "_dlt_load_id", "_dlt_id", "fields__slack_handle", "fields__board_leadership_experience", "fields__grant_writing_experience", "fields__state", "fields__city", "fields__nonprofit_experience_level", "fields__timezone", "fields__prior_volunteer_experience", "fields__tech_languages_tools", "fields__tech_experience_level", "fields__accommodations", "fields__employment_status", "fields__age_range", "fields__pronouns", "fields__github", "fields__other_notes", "fields__linkedin", "fields__website_portfolio", "fields__meeting_attendance" FROM "airtable_staging"."volunteers" WHERE "_dlt_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245)
INSERT INTO "airtable"."volunteers__fields__source"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__source"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__availability"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__availability"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__engagement_goals"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__engagement_goals"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__tech_skills"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__tech_skills"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__roles_interested_in"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__roles_interested_in"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__nonprofit_skills"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__nonprofit_skills"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__race"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__race"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__skills_to_develop"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__skills_to_develop"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          
INSERT INTO "airtable"."volunteers__fields__language_select"("value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id")                  SELECT "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                     FROM (                         SELECT ROW_NUMBER() OVER (partition BY "_dlt_id" ORDER BY (SELECT NULL)) AS _dlt_dedup_rn, "value", "_dlt_root_id", "_dlt_parent_id", "_dlt_list_idx", "_dlt_id"                         FROM "airtable_staging"."volunteers__fields__language_select"                     ) AS _dlt_dedup_numbered WHERE _dlt_dedup_rn = 1 AND ("_dlt_root_id" IN (SELECT * FROM volunteers_insert_33bf230cb593a2c05e350aeabe2bb245))          